#!/usr/bin/env python3
# The overlay icons RPCS3's renderer draws its dialogs with (extern/rpcs3/bin/
# Icons/ui/*.png), embedded so the core carries them into the sandbox: a guest
# has no host files. Emits one C++ source with the bytes and a table the
# driver installs into the memory filesystem at boot.
#
# Usage: gen-assets.py <icons dir> <out .cpp>
import os
import sys

src, out = sys.argv[1], sys.argv[2]
names = sorted(n for n in os.listdir(src) if n.endswith(".png"))
with open(out, "w") as f:
    f.write("// GENERATED by waterbox/gen-assets.py from extern/rpcs3/bin/Icons/ui; do not edit.\n")
    f.write("#include <cstddef>\n#include <cstdint>\n#include \"chimera-assets.h\"\n\n")
    for i, n in enumerate(names):
        data = open(os.path.join(src, n), "rb").read()
        f.write(f"static const uint8_t asset_{i}[{len(data)}] = {{")
        f.write(",".join(str(b) for b in data))
        f.write("};\n")
    f.write("\nconst chimera_asset chimera_assets[] = {\n")
    for i, n in enumerate(names):
        f.write(f'  {{"Icons/ui/{n}", asset_{i}, sizeof asset_{i}}},\n')
    f.write("};\n")
    f.write(f"const size_t chimera_asset_count = {len(names)};\n")
print(f"{len(names)} icons embedded")
