#!/usr/bin/env python3
# The overlay icons RPCS3's renderer draws its dialogs with (extern/rpcs3/bin/
# Icons/ui, ALL of it, subdirectories included), embedded so the core carries
# them into the sandbox: a guest has no host files. Emits one C++ source with
# the bytes and a table the driver installs into the memory filesystem at boot.
#
# The walk is recursive because a missing icon is not a missing picture, it is
# a dead machine: load_icon hands back an image_info with null data and zero
# width, the renderer builds a GL texture out of it, and rpcs3's own
# "Invalid OpenGL texture definition" ensure kills the RSX thread - after which
# every other thread waits forever on one that is gone. This globbed only
# ui/*.png once, which embedded 23 files and left the 36 under ui/home/32 and
# ui/home/256 out; the PS3 core then died in RSX bring-up on any title that
# opened the home menu overlay, hunting for Icons/ui/home/32/settings.png and
# the thirteen beside it. The whole tree is 360K.
#
# Usage: gen-assets.py <icons dir> <out .cpp>
import os
import sys

src, out = sys.argv[1], sys.argv[2]
# the two files the system messages are generated from (see below)
ids_header, strings_header = sys.argv[3], sys.argv[4]
# relative to <icons dir>, forward slashes, so the table's paths are the ones
# rpcs3 asks for: "Icons/ui/<name>" and "Icons/ui/home/32/<name>" alike
names = sorted(
    os.path.relpath(os.path.join(dirpath, n), src).replace(os.sep, "/")
    for dirpath, _dirs, files in os.walk(src)
    for n in files
    if n.endswith(".png"))
with open(out, "w") as f:
    f.write("// GENERATED by waterbox/gen-assets.py from extern/rpcs3/bin/Icons/ui; do not edit.\n")
    f.write("#include <cstddef>\n#include <cstdint>\n#include \"chimera-assets.h\"\n\n")
    for i, n in enumerate(names):
        data = open(os.path.join(src, n), "rb").read()
        f.write(f"static const uint8_t asset_{i}[{len(data)}] = {{")
        f.write(",".join(str(b) for b in data))
        f.write("};\n")
    f.write("\nconst chimera_asset chimera_assets[] = {\n")
    for i, n in enumerate(names):
        f.write(f'  {{"Icons/ui/{n}", asset_{i}, sizeof asset_{i}}},\n')
    f.write("};\n")
    f.write(f"const size_t chimera_asset_count = {len(names)};\n")

    # THE CONSOLE'S OWN MESSAGES. "Do you want to overwrite the saved data?", the
    # trophy notices, every system dialog: rpcs3 asks the FRONTEND for their
    # text, and its English lives in the Qt frontend (rpcs3qt/localized_emu.h),
    # which this build has no part of. A driver that answers with nothing draws
    # a confirmation that is two button icons and no question - which is what a
    # save over an existing one looked like (chimera issue 86). So the English is
    # lifted out at build time, by enum name, into a table indexed by the enum's
    # value: nothing to keep in step when rpcs3 adds a message.
    import re
    ids = re.findall(r"^\s*([A-Z][A-Z0-9_]*)\s*,?\s*$", open(ids_header).read(), re.M)
    text = dict(re.findall(r'case localized_string_id::(\w+):\s*return (?:tr\()?"((?:[^"\\]|\\.)*)"', open(strings_header, encoding="utf-8").read()))
    missing = [n for n in ids if n not in text and n != "INVALID"]
    f.write("\n// index = localized_string_id's value; \"\" where rpcs3 has no text\n")
    f.write("const char* const chimera_localized_text[] = {\n")
    for n in ids:
        f.write('  "%s", // %s\n' % (text.get(n, ""), n))
    f.write("};\n")
    f.write(f"const size_t chimera_localized_text_count = {len(ids)};\n")
    print(f"{len(text)} system messages ({len(missing)} ids without text)")
print(f"{len(names)} icons embedded")
