#!/usr/bin/env python3
# For every GL entry point glad knows but the bridge has no wrapper for, a trap
# that names itself: a core-profile renderer was assumed never to reach these,
# and when it does, the name is what the fix needs.
#
# Usage: gen-traps.py <glad gl.h> <generated-gl/gl-bridge-ops.h> <out .cpp>
import re
import sys

glad_h, ops_h, out = sys.argv[1:4]
known = set(re.findall(r'CHIMERA_GL_OP_(gl[A-Za-z0-9_]+)', open(ops_h).read()))
names = sorted(set(re.findall(r'^GLAD_API_CALL PFN[A-Z0-9_]+PROC glad_(gl[A-Za-z0-9_]+);', open(glad_h).read(), re.M)) - known)
with open(out, 'w') as f:
    f.write('// GENERATED by waterbox/gen-traps.py; do not edit.\n#include <cstdio>\n#include <cstdlib>\n#include <cstring>\n\n')
    f.write('extern "C" void chimera_gl_unbridged(const char* name);\n\n')
    for n in names:
        f.write(f'static void trap_{n}() {{ chimera_gl_unbridged("{n}"); }}\n')
    f.write('\nstruct trap_entry { const char* name; void (*fn)(); };\n')
    f.write('static const trap_entry traps[] = {\n')
    for n in names:
        f.write(f'  {{"{n}", trap_{n}}},\n')
    f.write('};\n\n')
    f.write('extern "C" void* chimera_gl_trap_lookup(const char* name)\n{\n')
    f.write('  for (const auto& t : traps)\n    if (strcmp(t.name, name) == 0)\n      return reinterpret_cast<void*>(t.fn);\n  return nullptr;\n}\n')
print(f'{len(names)} named traps')
