#!/usr/bin/env python3
# wiki-compat.json -> a C++ table the driver searches by title id.
# Usage: gen-wiki-compat.py <wiki-compat.json> <out .cpp>
import json
import sys


def c(s):
    """A C string literal, byte by byte: printable ASCII as is, everything else
    (quotes, backslashes, UTF-8 in Japanese titles) as octal escapes, so no
    title can break the source or smuggle a trigraph."""
    out = []
    for b in (s or "").encode("utf-8"):
        ch = chr(b)
        if 32 <= b < 127 and ch not in '"\\?':
            out.append(ch)
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


src, dst = sys.argv[1], sys.argv[2]
d = json.load(open(src, encoding="utf-8"))
kinds = {"settings": "s", "none": "n", "nopage": "p", "unread": "u"}
rows = sorted(d["titles"].items())
with open(dst, "w") as f:
    f.write("// GENERATED by waterbox/gen-wiki-compat.py from wiki-compat.json; do not edit.\n")
    f.write("// Source: the RPCS3 wiki (CC BY-SA 4.0) - see wiki-compat.json's _provenance.\n")
    f.write('#include <cstring>\n#include "wiki-compat.h"\n\n')
    f.write("const char* const chimera_wiki_snapshot = %s;\n" % c(d["_provenance"]["snapshot"]))
    f.write("const char* const chimera_wiki_compat_snapshot = %s;\n" % c(d["_provenance"].get("compatibility_snapshot") or d["_provenance"]["snapshot"]))
    f.write("const chimera_wiki_entry chimera_wiki[] = {\n")
    for tid, e in rows:
        # what the wiki says, in its words, for the reader; and the same
        # recommendations as the settings they become, for the frontend
        applied = ", ".join(e.get("applied") or [])
        values = json.dumps(e["apply"], separators=(",", ":")) if e["apply"] else ""
        f.write("  { %s, %s, %s, '%s', %s, %s, %s, %s },\n" % (
            c(tid), c(e["title"]), c(e.get("status") or ""), kinds[e["kind"]],
            c(e["page"]), c(applied), c(", ".join(e["unsupported"])), c(values)))
    f.write("};\n")
    f.write("const size_t chimera_wiki_count = %d;\n\n" % len(rows))
    f.write("""const chimera_wiki_entry* chimera_wiki_find(const char* title_id)
{
  if (!title_id || !*title_id) return nullptr;
  size_t lo = 0, hi = chimera_wiki_count;
  while (lo < hi)
  {
    const size_t mid = lo + (hi - lo) / 2;
    const int c = std::strcmp(chimera_wiki[mid].id, title_id);
    if (c == 0) return &chimera_wiki[mid];
    if (c < 0) lo = mid + 1; else hi = mid;
  }
  return nullptr;
}
""")
print("%d titles -> %s" % (len(rows), dst))
